fs   = require('fs')
path = require('path')


exports.prepare = (rootPath, cb) ->

  # Create .awe/ directory
  cachePath = path.join(rootPath, '.awe')

  await fs.mkdir(path.join(cachePath), defer err)
  return cb(err) if err and err.code != 'EEXIST'

  # Create awe/.gitignore
  gitignore = path.join(cachePath, '.gitignore')
  fs.writeFile(gitignore, '# Automatically generated by Awe - ignore all files\n*\n', cb)

  cb(null, cachePath)
